IKnowMed inital Integration, EHR Administration Page and IKnowMed edit integration Drawer Form
Umbrage-Studios/cover-my-meds pull request #32
Opened 2024-05-29 16:01 UTC by ejbelville

![image](https://github.com/Umbrage-Studios/cover-my-meds/assets/22043478/1ec006dc-6f7a-4972-9c6a-28a0b1d70dc8)

I also removed some various errors arising from the sign-up page to clean up the console.

2024-05-29 17:11 UTC, MrDiggles2 approved these changes
LGTM! Left some minor feedback

2024-05-29 17:11 UTC, MrDiggles2 commented on apps/frontend/src/app/models/EHRIntegration.ts
> +    Epic = 'Epic',
These should match the backend values, see `apps/backend/src/app/app-modules/ehr-integration/ehr-integration.types.ts`

```
export enum EhrIntegrationType {
  IKNOWMED = 'IKNOWMED',
  EPIC = 'EPIC'
}
```

2024-05-29 17:11 UTC, MrDiggles2 commented on apps/frontend/src/app/models/EHRIntegration.ts
> +    },
Just a heads up - this `config` can be a different value based on if it's an iknowmed or epic integration

2024-05-29 17:11 UTC, MrDiggles2 commented on apps/frontend/src/app/models/EHRIntegration.ts
> +    },
i.e. the epic integration looks like it'll be something like

```
config: {
    clientId: string;
    publicKey: string;
    privateKey: string;
}
```

I'll have a PR up for the backend shortly with the different types

2024-05-29 17:44 UTC, MrDiggles2 requested changes

2024-05-29 17:44 UTC, MrDiggles2 commented on apps/frontend/src/app/pages/signup-page/ehr-integration-form/i-know-meds-form.tsx
> +    organizationId: currentOrganization?.id,
I'm getting a couple of instances where organization loads after this state is set which causes the API request to fail due to missing org ID.

Can we update this to be set via an effect? Something like

```
useEffect(() => {
    setForm({...form, organizationId: currentOrganization.id})
}, [currentOrganization])
```

2024-05-29 18:05 UTC, ejbelville commented on apps/frontend/src/app/models/EHRIntegration.ts
> +    },
Great, I'm working on adding the Epic Form now and am handling the different types as I come across them. So this'll be updated in my next PR.

2024-05-29 18:05 UTC, ejbelville commented on apps/frontend/src/app/pages/signup-page/ehr-integration-form/i-know-meds-form.tsx
> +    organizationId: currentOrganization?.id,
Added

2024-05-29 18:05 UTC, ejbelville commented on apps/frontend/src/app/models/EHRIntegration.ts
> +    Epic = 'Epic',
Done!

2024-05-30 15:45 UTC, MrDiggles2 approved these changes
LGTM! 🚢

2024-05-31 16:43 UTC, merged